### ISSUE TITLE
Disruptive changes in Melodic

### ISSUE THREAD

**Issue by j-rivero** [ros-simulation/gazebo_ros_pkgs#725]
Here is the list of disruptive changes to be commited into Melodic that could require user reaction. Sorry for not doing them before the final release but I think it is a good time to made them:

### Joint Pose Trajectory
 - [x] Remove the `gazebo_ros_joint_pose_trajectory` item (pr #708)
### Gazebo ROS Control
 - [x] Remove legacy option from `gazebo_ros_control` in order not to ignore robotNamespace (pr #637, pr #709) 
### Diff Drive plugin
 - [x] Change encoder mode to send velocity from odom frame to base_link frame (#issue #717, pr #719)
 - [x] Remove legacy protection about the inversion of right and left wheels in code (pr #707)
### Spawn Model
 - [x] Remove -gazebo option from spawnmodel (deprecated in ROS Hydro) (issue #729)

**Comment by kev-the-dev** [comment]
Recommend adding 
* [ ] remove ```-gazebo``` option from spawnmodel (deprecated in ROS Hydro), issue #729

**Comment by davetcoleman** [comment]
Thanks @j-rivero for taking care of these migration changes, very important!

**Comment by kev-the-dev** [comment]
All items are now merged in melodic.
